### ISSUE TITLE
issues in vendors

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books-mobile#105]
- [x] inactive vendor name must not be displayed under listing of creation screen of any module
- [x] vendor names are getting duplicated each time clicking on vendor field under all modules  of purchase
- [x] no option to check whether vendor is active or inactive under listing or display screen

**Comment by rishal-ahmed** [comment]
Fixed!

**Comment by AnjaliVellookkaran** [comment]
please re-check the first issue @rishal-ahmed @SangeethCK

**Comment by AnjaliVellookkaran** [comment]
issue fixed !
