### ISSUE TITLE
Purchase bills

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books-mobile#106]
- [x] remove kebab button from reject status display screen
- [x] account column needed in creation screen
- [x] customer field need to add
- ![Screenshot from 2023-10-21 14-35-03](https://github.com/techgebra/polosys-books-mobile/assets/131741149/4a36e8e0-0a36-458e-adae-d90392f0b54e)

- [x] status change response message is not displayed
- [x] validation message is not dispalyed

**Comment by avandhikaashokan** [comment]
issue closed
