### ISSUE TITLE
Bugs in recurring invoice

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books-mobile#113]
- [x] remove invoice number field
- [x] when never expire is ticked,end date format must be dd/mm/yyyy
- [x] rename repeat every as repeat
- [x] add sales order number field
- [x] **remove * from **start date****
- [x] there is a blank space under billed / add items
- [x] remove reference field
- [x] **recurring invoice number is not displayed under detail page**
- [x] rename invoice status to profile status under detail page
- [x] attach file is not working
- [x] not able to create new frequency
- [x] **make description field under repeat every as non-mandatory**
![screenshot_2023-12-17-14-50-38-606_com polosys books_720](https://github.com/techgebra/polosys-books-mobile/assets/138277245/ad39f954-72a6-472a-b712-21b8f831dc59)

- [x] frequency select under repeat is in incorrect format
- [x] no validation message on the screen of frequency creation
- [x] add status column in listing page

**Comment by avandhikaashokan** [comment]
- [x] recurring invoice  creation  not functioning

**Comment by avandhikaashokan** [comment]
issue closed
