### ISSUE TITLE
Bugs while creating new transactions from customers

### ISSUE THREAD

**Issue by AnjaliVellookkaran** [techgebra/polosys-books-mobile#114]
-  creation of invoice
- [x] remove discount field
- [x] make payment terms as mandatory(add *)
- [x] add supply date field,order no field
- creation of customer payment
- [x] add default values for payment mode,deposit to account field as cash and main safe respectively
- [x] remove amount in excess and amount to be refunded
- [x] remove discount field
- [x] sales order no is displayed as NEW
- [x] while doing customer payment ,customer name not populated
- [x] payment# not showing
- [x] two check box with same functionality is available .so rename one check box name to Apply amount
- [x] if we input amount on amount received ,don't auto populate the entered amount under unpaid invoice
- [x] once customer payment is done .again follow the same customer payment updated amount due is not calculated
- [x] unpaid invoices(please discuss it with sahal for more info)
- creation of  delivery challan
- [x] remove blank space under items table
- creation of recurring invoices
- [x] customer name is not displayed
- [x] remove invoice no. field
- [x] add sales order no. field
- [x] **refer Bugs in recurring invoices (issue no:113)**
- creation of Expenses
- [x] remove * from date field
- [x] under amount field,currency must be properly displayed
- [x] remove default value from employee field
- [x] employee field is listing sales person data
- [x] add place of supply field 
- [x] **please refer Bugs in expenses (issue no:112)**
- journal
- [x] journal no is missing
- [x] should show currency in default
- [x] do not display the exchange rate field only for the currency used when creating an organisation
- [x] ** please refer Bugs in Journal(issue no:73)**
- Creation of sales return
- [x] remove due date field
- [x] rename return receipt number to sales return no.
- [x] add * for invoice field
- [x] add transaction type field
- [x] remove extra blank space below the items table 
- [x] some times we can change the place of supply customer who has tax treatment as non vat registered 
- Retainer Invoice
- [x] retainer invoice is created without adding amount
- [x] remove discount field
- recurring invoice
- [x] customer name and place of supply not populated
- [x] customer - recurring invoice creation not working
- Sales return
- [x] return receipt number not showing
- [x] rename return receipt number to sales return number\
- [x] remove due date

**Comment by avandhikaashokan** [comment]
issue closed
