### ISSUE TITLE
issue in add item table : under sales and purchase module

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books-mobile#216]
- [ ] search using SKU not functioning
- [ ] 
![screenshot_2024-01-24-11-17-10-207_com polosys books_720](https://github.com/techgebra/polosys-books-mobile/assets/138277245/22a45184-df79-409a-9341-35667b781e25)

**Comment by naveenjosetg** [comment]
need to discuss with backend team  what the query string is

**Comment by avandhikaashokan** [comment]
issue closed
