### ISSUE TITLE
Item bugs

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books-mobile#26]
- [x] Message for name duplicate message for clone; if user not enable duplication through preferences.
- [x] Change column order under purchase and sales information; price show above description.
- [x] Item with opening stock can't delete with such opening stock. need notification for such item deletion
- [x] No need to show barcode at the time of generation.
- [x] Barcode generation not working second time.
- [x] Disable group selection in drop down. eg:- purchase account, sales account and inventory account.
- [x] Decimal not working in opening stock value.
- [x] Opening stock quantity decimal issue.
- [x] Re order level decimal issue.
- [x] No option to add image by using camera in detailed page.
- [x] Item image not shown for editing in item edit screen.
- [x] Track inventory button disabled at the time of edit for item created with opening stock. (created from web; edited from mobile)
- [x] Track inventory button disabled at the time of edit for item created with opening stock. (created from mobile; edited from web)
- [x] Re-order column blank at the time of edit.
- [x] After add image pointer navigate to re order point column.
- [x] Vendors are not listed to select preferred vendor in item creation screen.
- [x] Spelling mistake in 'Preferred Vendor'.
- [x] Advance search button in item detailed view.
- [x] No need to show quantity for services and inventory tracking disabled items.
- [x] Availability zone 'a' missing in available.
- [x] Preferred vendor not a mandatory field.
- [x] tax type should be mandatory field (*)

**Comment by avandhikaashokan** [comment]
bug fixed
