### ISSUE TITLE
Item Bugs 2.0

### ISSUE THREAD

**Issue by MohdSahal** [techgebra/polosys-books-mobile#27]
- [x] After barcode generation selection will be navigate to next field.
- [x] Close button shown at the time of creation(availability zone) - even no data selected.
- [x] After image pickup selection button navigate to opening stock rate.
- [x] Image not shown in creation screen.
- [x] Default report unit column shown value given in default sales unit.
- [x] After clone creation of an item; next screen will be item listing page. (currently navigate to detailed screen of old item)
- [x] Sales description missing at the time of clone and edit.
- [x] Track inventory system enabled at the time of new item creation.
- [x] Unit section is not editable; if such item used in previous transactions.
- [ ]

**Comment by avandhikaashokan** [comment]
bug fixed
