### ISSUE TITLE
bug in estimates

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books-mobile#49]
- [x] estimate clone option not working
- [x] advance search not working 
- [x] convert to invoice not working 
- [x] spelling error in declained,send(declined).so filter for sent and declined not working
- [x] print not working fine
- [x] estimate download not working
- [x] response message is not showing for creation,updation,deletion
- [x] save and send not working
- [x] edit not working
- [x] while creating estimate with status save and submitt it showing with the status draft
- [x] after creating new estimate ,it is disappearing from listing
- [x] Grand total not same as the total amount( so, Grand total in detail page should kept same as  total amount in the creation page)
- [x] advance search using customer not working 
- [ ] ~billing/shipping address creation not functioning while creating estimate (it showing error message)~
- [x] while convert to draft , reason filed should kept required
- [x] if we  add/delete comment ,the result showing only after reopen the estimate detail page
- [x] reason for converting to draft is accepting blank spaces
- [x] while converting to invoice,estimate number SE1 must be displayed in reference field not in invoice number field.
- [x] remove convert to invoice option from draft status and declined status
- [x] need to add a popup window for converting to invoice from invoiced status
- ![Screenshot from 2023-10-21 15-06-02](https://github.com/techgebra/polosys-books-mobile/assets/131741149/3a4cdfac-7d94-418e-9c27-c6c7127066e5)
- [x] while selecting the pricelist , it is not showing the selected pricelist
- [x] inactive price list is showing while selecting pricelist from pricelist drop-down
- [x] filter not working fine - sent,declined, invoiced
- [x] sort by  not working- Name ,last modified time
- [x] remove normal search
- [x] place holder name are interchanged in advance search

**Comment by AnjaliVellookkaran** [comment]
issues fixed !
