### ISSUE TITLE
Bug in delivery challan

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books-mobile#53]
- [x] Advance search is not working fine
- [x] rename delivery challan to delivery challans under heading of listing page
- [x] remove default dates from date range field under advanced search page
- [x] sort option not working - name,delivery challan no
- [x] user is able to create delivery challan without adding items
- [x] convert to invoice not working
- [x] some times address not found while creating delivery challan
- [x] after creating delivery challan some data not auto populated they are
- [x] place of supply-showing [null]-saudi arabia under edit page
- [x] sales person
- [x] price list 
- [x] terms and conditions
- [x] extra field is available in app - additional charges,(home icon)
- [x] response message not mentioned for create,update ,delete
- [x] remove * from tax
- [x] reference not  accepting small letters
- [x] edit not functioning(it shows sales person id invalid pk)
- [x] remove normal search

**Comment by AnjaliVellookkaran** [comment]
issues fixed !
