### ISSUE TITLE
purchase bill

### ISSUE THREAD

**Issue by avandhikaashokan** [techgebra/polosys-books-mobile#96]
- [x] while doing reject , reason should be added (it is mandatory)
- [x] purchase bill with the status rejected , can't apply purchase return 
- [x] while save record payment ,first it showing error message(payment mode id invalid pk) then it showing successfully added message but payment not recorded
- [x] The pop up screen remaining there ,after creating purchase return 
- [x] **expected delivery date**  not mentioned
- [x] reference rename to reference number(also in record payment)
- [x] validation messages are not given for mandatory fields
- [x] save is not working for convert to purchase return option of paid status bills
- [x] remove kebab button under rejected status bills
- [x] ~remove pricelist field~
- [x] add account and customer field under items detail table under creation screen
- [x] status change response message is not displaying 
- [x] clone is not working
- [x] rename bill number to purchase invoice number
- [x] validation message for required field not mentioned

**Comment by AnjaliVellookkaran** [comment]
@SangeethCK please recheck all these issues

**Comment by avandhikaashokan** [comment]
issue closed
